import Head from 'next/head'
import { Link as Scroll } from 'react-scroll';
import styles from '../styles/Home.module.scss'

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>粉鶴亀のポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1 id="title" className={styles.headerTitle}>
            粉鶴亀のポートフォリオ
        </h1>
          <nav id="global-navi">
            <ul>
              <li><Scroll to="works-section" smooth={true}>WORKS</Scroll></li>
              <li><Scroll to="concept-section" smooth={true}>CONCEPT</Scroll></li>
              <li><Scroll to="news-section" smooth={true}>NEWS</Scroll></li>
            </ul>
          </nav>
        </header>

      <main className={styles.main}>
        <div className={styles.mainTitle}>
          <img className={styles.myLogo} src="./sample_logotype.svg" />
        </div>
        <section>
          ABOUT
        </section>
        <section className={styles.section} id="works-section">
          <header className={styles.sectionHeader}>
            <h1>WORKS</h1>
          </header>
          <div className={styles.sectionContainer}>
            <p>WORKS</p>
          </div>
        </section>
        <section className={styles.section} id="concept-section">
          <header className={styles.sectionHeader}>
            <h1>CONCEPT</h1>
          </header>
          <div className={styles.sectionContainer}>
            <p>CONCEPT</p>
          </div>
        </section>
        <section className={styles.section} id="news-section">
          <header className={styles.sectionHeader}>
            <h1>NEWS</h1>
          </header>
          <div className={styles.sectionContainer}>
            <p>NEWS</p>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;
