import Head from 'next/head';
import Link from 'next/link';
import { Link as Scroll } from 'react-scroll';
import styles from '../styles/Home.module.scss';

const works = [] as string[];
for (let i = 0; i < 18; i++) {
  works.push("/sample_image.png");
}

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>粉鶴亀のポートフォリオ</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <h1 id="title" className={styles.headerTitle}>
          <Link href="/">粉鶴亀のポートフォリオ</Link>
        </h1>
          <nav id="global-navi">
            <ul>
              <li className={styles.navItem}><Scroll to="works-section" smooth={true}>WORKS</Scroll></li>
              <li className={styles.navItem}><Scroll to="concept-section" smooth={true}>CONCEPT</Scroll></li>
              <li className={styles.navItem}><Scroll to="news-section" smooth={true}>NEWS</Scroll></li>
            </ul>
          </nav>
        </header>

      <main className={styles.main}>
        <div className={styles.mainTitle}>
          <img className={styles.myLogo} src="./sample_logotype.svg" />
        </div>
        <section id="about-section">
          <div id={styles.aboutContainer}>
            <div className={styles.iconContainer}>
              <img className={styles.icon} src="./icon.jpeg"/>
            </div>
            <div className={styles.descriptionContainer}>
              <div className={styles.description}>
                <p>粉鶴亀（こなつるか）</p>
                <p>アニメーター</p>
                <p>MP・TVアニメ</p>
                <p>イラスト・マンガ</p>
              </div>
              <div className={styles.description}>
                <p>主な仕事：<br />
                  <a href="https://www.youtube.com/watch?v=ENcnYh79dUY">ヨルシカ「思想犯」</a><br />
                  <a href="https://www.youtube.com/watch?v=kzdJkT4kp-A">YOASOBI「ハルジオン」</a>
                </p>
                <p>連絡先：...@gmail.com</p>
                <p>Twitter:<a href="https://twitter.com/sashimi0404">@sashimi</a></p>
              </div>
            </div>
          </div>

        </section>
        <section className={styles.section} id="works-section">
          <header className={styles.sectionHeader} id={styles.worksHeader}>
            <h1>WORKS</h1>
          </header>
          <div className={styles.sectionContainer}>
            {works.map((source) => (<figure className={styles.work} key={source}>
              <img src={source}/>
            </figure>))}
          </div>
        </section>
        <section className={styles.section} id="concept-section">
          <header className={styles.sectionHeader} id={styles.conceptHeader}>
            <h1>CONCEPT</h1>
          </header>
          <div className={styles.sectionContainer}>
            <p>CONCEPT</p>
          </div>
        </section>
        <section className={styles.section} id="news-section">
          <header className={styles.sectionHeader} id={styles.newsHeader}>
            <h1>NEWS</h1>
          </header>
          <div className={styles.sectionContainer}>
            <p>NEWS</p>
          </div>
        </section>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <img src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;
